app.config:
  session:
    default_locale: en

## Doctrine Configuration
doctrine.dbal:
  dbname: xxxxxxxx
  user: xxxxxxxx
  password: ~
  host: ~

## Swiftmailer Configuration
swiftmailer.config:
  transport: smtp
  encryption: ssl
  auth_mode: login
  host: smtp.gmail.com
  username: xxxxxxxx
  password: xxxxxxxx

## DoctrineUserBundle
doctrine_user.config:
  db_driver: orm
  class:
    model:
      user: Application\YrchBundle\Entity\User
  confirmation_email:
    enabled: true
    from_email: xxxxx@xxxxx.xx

## YrchBundle configuration
yrch.config:
  special_user:
    username: yrchstaff
    nick: Yrch! Staff
